import { supabase } from './supabase.ts';

/**
 * Checks whether a display name is auto-generated (e.g. Player1234), vs. one the
 * player actually chose.
 */
export function isAutoGeneratedDisplayName(name?: string | null): boolean {
  if (!name || !name.trim()) return true;
  const trimmed = name.trim();
  if (trimmed.toLowerCase() === 'player') return true;
  if (/^player\d+$/i.test(trimmed)) return true;
  return false;
}

/**
 * Validates display name criteria: required, 2 to 20 characters.
 */
export function validateDisplayNameFormat(name: string): { valid: boolean; error?: string } {
  const trimmed = name.trim();
  if (!trimmed) return { valid: false, error: 'Display name is required' };
  if (trimmed.length < 2) return { valid: false, error: 'Display name must be at least 2 characters' };
  if (trimmed.length > 20) return { valid: false, error: 'Display name must be 20 characters or less' };
  return { valid: true };
}

/**
 * Checks if a display name is already taken by another player.
 */
export async function checkDisplayNameTaken(
  name: string,
  excludeUserId?: string | null
): Promise<{ taken: boolean; error?: string }> {
  const trimmed = name.trim();
  const formatCheck = validateDisplayNameFormat(trimmed);
  if (!formatCheck.valid) return { taken: false, error: formatCheck.error };

  try {
    let query = supabase.from('profiles').select('id, display_name').ilike('display_name', trimmed);
    if (excludeUserId) query = query.neq('id', excludeUserId);
    const { data } = await query.maybeSingle();
    if (data && data.id) return { taken: true, error: 'That name is taken, try another' };
    return { taken: false };
  } catch (err) {
    console.warn('Display name check exception:', err);
    return { taken: false };
  }
}
